version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: akkipy-postgres
    restart: always
    environment:
      POSTGRES_USER: ${LOCAL_POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${LOCAL_POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --port 6379
    networks:
      - app-network

#  app:
#    build: .
#    container_name: app
#    depends_on:
#      - redis
#    environment:
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379
#      - SPRING_REDIS_PASSWORD=yourStrongRedisPass
#    networks:
#      - app-network
#    ports:
#      - "8080:8080"


  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=backtony
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - app-network



volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge