spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: server
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${LOCAL_POSTGRESQL_HOST}:${LOCAL_POSTGRESQL_PORT}/${DB_NAME}
    username: ${LOCAL_POSTGRESQL_USERNAME}
    password: ${LOCAL_POSTGRESQL_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    logging:
      level:
        org:
          hibernate:
            type:
              descriptor:
                sql: trace
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-url: ${KAKAO_REDIRECT_URL}
  admin-key: ${KAKAO_ADMIN_KEY}

firebase:
  api-key: ${FIREBASE_API_KEY}

naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-url: ${NAVER_REDIRECT_URL}
jwt:
  secret: ${JWT_SECRET_KEY}
  guest-token:
    expiration: ${JWT_GUEST_TOKEN_EXPIRATION}
  access-token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}